name: anitamorrow
favicon: null
layout_spectrum: 0.99711
typography_spectrum: 0.05009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffb2cd'
    - '#860024'
    - '#882845'
    - '#b64d70'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.14710772829130292
purpose: []
